services:
  external-service:
    image: wiremock/wiremock:2.33.2
    command: "--port 80 --verbose"
  my-service:
    build: 
      context: .
    environment:
      - "EXTERNAL_SERVICE_URL=http://external-service"
  integration-tests:
    build: 
      context: ./integration-tests
    environment:
      - "MY_SERVICE_URL=http://my-service"
      - "EXTERNAL_SERVICE_URL=http://external-service"
    depends_on:
      - external-service
      - my-service
